### ISSUE TITLE
Fix build failing on Travis due to Travis upgrade of jdk

### ISSUE THREAD

**Issue by apupier** [camel-tooling/camel-tooling-common#50]
$ \~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
Ignoring license option: BCL -- using GPLv2+CE by default
install-jdk.sh 2019-07-17
Expected feature release number in range of 9 to 14, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .

**Comment by djelinek** [comment]
verified with master branch
